name: Performance Issue
description: Report a performance problem or regression
title: "[Performance]: "
labels: ["performance", "needs-triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a performance issue! Performance data helps us improve the template.

  - type: textarea
    id: description
    attributes:
      label: Performance Issue Description
      description: Describe the performance problem
      placeholder: The application is slow when...
    validations:
      required: true

  - type: dropdown
    id: area
    attributes:
      label: Affected Area
      description: Which part of the application has the performance issue?
      options:
        - Startup time
        - UI rendering
        - Configuration load/save
        - Logging
        - Localization
        - Build time
        - Test execution
        - Memory usage
        - Other
    validations:
      required: true

  - type: textarea
    id: measurements
    attributes:
      label: Performance Measurements
      description: Provide specific measurements (timing, memory usage, FPS, etc.)
      placeholder: |
        Before: 100ms
        After: 500ms

        Or profiler output...
      render: shell
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: How to reproduce the performance issue
      placeholder: |
        1. Open application
        2. Perform action X
        3. Measure time/memory
    validations:
      required: true

  - type: dropdown
    id: severity
    attributes:
      label: Severity
      description: How severe is the performance impact?
      options:
        - Minor - Barely noticeable
        - Moderate - Noticeable but usable
        - Severe - Significantly impacts usability
        - Critical - Makes feature unusable
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment Details
      description: OS, compiler, build type, hardware specs
      placeholder: |
        OS: Ubuntu 22.04
        Compiler: GCC 11
        Build: Release
        CPU: Intel i7-9700K
        RAM: 16GB
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: MetaImGUI Version
      description: Version or commit hash
      placeholder: v1.3.0
    validations:
      required: true

  - type: textarea
    id: regression
    attributes:
      label: Regression Information
      description: Did this work faster in a previous version? Which one?
      placeholder: This was fast in v1.2.0 but slow in v1.3.0
    validations:
      required: false

  - type: textarea
    id: profiling
    attributes:
      label: Profiling Data
      description: Attach profiler output, flamegraphs, or benchmark results if available
      placeholder: Paste profiler output or attach files...

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other relevant information
      placeholder: Additional information...

